services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - ../.env
    volumes:
      - ../:/app
    command: sleep infinity
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ../.env
